AssetManagement/Controllers/AssetAccountController.cs
using AssetManagement.DAL;
using AssetManagement.Models;
using System.Collections.Generic;
using System.Web.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Web;
using System.IO;
using System.Linq;
using System.Globalization;

namespace AssetManagement.Controllers
{
    public class AssetAccountController : Controller
    {
        AssetDetailsDAL assetDetailsDal = new AssetDetailsDAL();
        List<CommitteeDetails> managementLst = new List<CommitteeDetails>();
        List<CommitteeDetails> advisoryLst = new List<CommitteeDetails>();
        // GET: AssetAccount

        public ActionResult OpenAccountPage()
        {
            assetDetailsDal.setSessionToNull();
            ViewBag.login = "Logout";
            ViewBag.isAdmin = "admin";
            return View("~/Views/LoginReg/OpenAccountPage.cshtml");
        }
        public ActionResult OpenAddAsset()
        {
            ViewBag.login = "Logout";
            return PartialView("~/Views/AssetAccount/OpenAsset.cshtml");
        }

        public ActionResult AddAsset(string assetType)
        {
            assetDetailsDal.setSessionToNull();
            ViewBag.login = "Logout";
            AssetViewModels model = new AssetViewModels();

            model.populateAssetViewModel();
            model.assetTypeFlow = assetType;
            ViewBag.assetFlow = "AddAsset";
            ViewBag.managementDetails = "AddAsset";
            ViewBag.advisoryDetails = "AddAsset";
            if (assetType == "MainAsset")
            {
                return View("~/Views/AssetAccount/AddMainAsset.cshtml", model);
            }
            else
            {
                Dictionary<string, string> list = assetDetailsDal.getMainAssetName();

                if (list.Count != 0)
                {
                    return View("~/Views/AssetAccount/AddSubAsset.cshtml", model);
                }
                else
                {
                    ViewBag.isAdmin = HttpContext.Session["isAdmin"];
                    ViewBag.isException = "set";
                    return View("~/Views/LoginReg/OpenAccountPage.cshtml");
                }

            }
        }

        public ActionResult AddManagementDetails()
        {

            return PartialView("~/Views/AssetAccount/PartialAddManagementDetails.cshtml");
        }

        public ActionResult SaveAssetInformtaion(AssetViewModels model)
        {
            try
            {
                foreach (var i in model.selectedAssetTypeList)
                {
                    model.selectedAssetType += i + "|";
                }

                if (model.assetTypeOthers != "" && model.assetTypeOthers != null)
                {
                    model.selectedAssetType += model.assetTypeOthers;
                }

                foreach (var i in model.selectedAssetStatusList)
                {
                    model.selectedAssetStatus += i + "|";
                }

                if (model.assetStatusOthers != "" && model.assetStatusOthers != null)
                {
                    model.selectedAssetStatus += model.assetStatusOthers;
                }
                ViewBag.login = "Logout";

                //get the value of the selected radio button and assign it to model

                if (model.rdBtnType == "rural")
                {
                    model.rural = model.rdBtnType;
                }
                else
                {
                    model.urban = model.rdBtnType;
                }
                bool status = assetDetailsDal.saveInstitutionInformation(model);
                assetDetailsDal.setSessionToNull();
                if (status)
                {
                    ViewBag.isAdmin = HttpContext.Session["isAdmin"];
                    return View("~/Views/LoginReg/OpenAccountPage.cshtml");
                }
                else
                {
                    return View("~/Views/LoginReg/OpenAccountPage.cshtml");
                }

            }
            catch (System.Exception)
            {

                throw;
            }

        }

        public ActionResult RemoveAsset()
        {
            ViewBag.login = "Logout";
            JArray assetDetailsLst = assetDetailsDal.getListOfAssets();
            ViewBag.data = assetDetailsLst;
            return View();
        }

        public ActionResult RemoveInstitutionsFromDB(string institutionId)
        {
            ViewBag.login = "Logout";
            assetDetailsDal.removeInstitutionFromDB(institutionId);
            return View("~/Views/AssetAccount/RemoveAsset.cshtml");
        }

        public ActionResult OpenEditAsset()
        {
            ViewBag.login = "Logout";
            JArray assetDetailsLst = assetDetailsDal.getListOfAssets();

            ViewBag.data = assetDetailsLst;
            return View("~/Views/AssetAccount/OpenEditAsset.cshtml");

        }


        public ActionResult EditAsset(string institutionId)
        {
            ViewBag.login = "Logout";
            AssetViewModels model = new AssetViewModels();
            ViewBag.assetFlow = "EditAsset";
            model.populateAssetViewModel();

            model = assetDetailsDal.getAssetDetailsForEditFLow(institutionId, model);

            if (model.selectedDivision != null)
            {
                List<string> distLst = assetDetailsDal.getDistrict(model.selectedDivision);
                model.district = (from item in distLst
                                  select new SelectListItem
                                  {
                                      Text = item,
                                      Value = item
                                  }).ToList();
            }

            if (model.selectedDistrict != null)
            {
                List<string> talukLst = assetDetailsDal.getTaluk(model.selectedDistrict);
                model.taluk = (from item in talukLst
                               select new SelectListItem
                               {
                                   Text = item,
                                   Value = item
                               }).ToList();


                List<string> mpLst = assetDetailsDal.getMPList(model.selectedDistrict);
                model.MPConstituency = (from item in mpLst
                                        select new SelectListItem
                                        {
                                            Text = item,
                                            Value = item
                                        }).ToList();

                List<string> mlaLst = assetDetailsDal.getMLAList(model.selectedDistrict);
                model.MLAConstituency = (from item in mlaLst
                                         select new SelectListItem
                                         {
                                             Text = item,
                                             Value = item
                                         }).ToList();






            }

            if (model.selectedTalukPanchayat != null)
            {
                List<string> tempLst = new List<string>();
                tempLst.Add(model.selectedTalukPanchayat);
                List<string> talukPLst = tempLst;
                model.talukPanchayat = (from item in talukPLst
                                        select new SelectListItem
                                        {
                                            Text = item,
                                            Value = item
                                        }).ToList();
            }


            if (model.selectedTalukPanchayat != null)
            {
                List<string> villagePanchayathLst = assetDetailsDal.getVillagePanchayath(model.selectedTalukPanchayat);
                model.gramaPamchayat = (from item in villagePanchayathLst
                                        select new SelectListItem
                                        {
                                            Text = item,
                                            Value = item
                                        }).ToList();
            }

            if (model.selectedGramaPanchayat != null)
            {
                List<string> villageLst = assetDetailsDal.getVillage(model.selectedGramaPanchayat);
                model.village = (from item in villageLst
                                 select new SelectListItem
                                 {
                                     Text = item,
                                     Value = item
                                 }).ToList();
            }


            Char delimiter = '|';

            if (model.selectedAssetType != null)
            {
                String[] words = model.selectedAssetType.Split(delimiter);

                foreach (var i in words)
                {
                    if (i != "")
                    {
                        model.selectedAssetTypeList.Add(i);
                    }
                }
            }


            if (model.selectedAssetStatus != null)
            {
                String[] words = model.selectedAssetStatus.Split(delimiter);

                foreach (var i in words)
                {
                    if (i != "")
                    {
                        model.selectedAssetStatusList.Add(i);
                    }
                }
            }


            List<string> assetStatusImageLst = new List<string>();
            foreach (var i in model.assetStatusImages)
            {
                assetStatusImageLst.Add(i.fileName + "|" + i.imageSize);
            }
            createDirAndImage(model.assetStatusImages);
            ViewBag.assetStatusImageLst = assetStatusImageLst;

            List<string> gnNumberImageLst = new List<string>();
            foreach (var i in model.gnNumberImages)
            {

AssetManagement/Controllers/LoginRegController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AssetManagement.Models;
using AssetManagement.DAL;
using Newtonsoft.Json.Linq;

namespace AssetManagement.Controllers
{
    public class LoginRegController : Controller
    {
        AssetDetailsDAL assetDetailsDal = new AssetDetailsDAL();
        public ActionResult OpenLogin()
        {
            ViewBag.login = "Login";
            return View();
        }


        public ActionResult LoginCheck(CustomLoginRegViewModel model)
        {
            try
            {
                LoginRegDAL lr = new LoginRegDAL();
                bool status = lr.loginCheck(model.Email,model.Password);
                
                if (status)
                {
                    ViewBag.login = "Logout";
                    ViewBag.isAdmin = "admin";
                    Session["isAdmin"] = "admin";
                    return View("~/Views/LoginReg/OpenAccountPage.cshtml");
                }
                else
                {
                    ViewBag.message = "The email and password you entered don't match.";
                    return View("~/Views/LoginReg/OpenLogin.cshtml");
                }
            }
            catch (Exception exc)
            {
                return View();
            }
            
        }

        public ActionResult Logout()
        {
            ViewBag.login = "Login";
            Session["isAdmin"] = null;
            JArray jarray = assetDetailsDal.getMarkersFromDB();
            ViewBag.getMarkers = jarray;
            return View("~/Views/Home/Index.cshtml");
        }
    }
}

AssetManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link href="~/Content/datepicker.min.css" rel="stylesheet" />
    <link href="~/font-awesome-4.5.0/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/Content/jsgrid.min.css" rel="stylesheet" />
    <link href="~/Content/jsgrid-theme.min.css" rel="stylesheet" />
    <link href="~/Content/dropzone.css" rel="stylesheet" />
    <link href="~/Content/chosen.min.css" rel="stylesheet" />

</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <!-- Include Bootstrap Wizard -->
    <script src="~/Scripts/jquery-ui.min.js"></script>
    <script src="~/Scripts/jquery.bootstrap.wizard.min.js"></script>
    <script src="~/Scripts/formValidation.min.js"></script>
    <script src="~/Scripts/formValidation.bootstrap.min.js"></script>
    <script src="~/Scripts/bootstrap-datepicker.min.js"></script>
    <script src="~/Scripts/assestManagementFormFlow.js"></script>
    <script src="~/Scripts/jsgrid.min.js"></script>
    <script src="~/Scripts/dropzone-amd-module.js"></script>
    <script src="~/Scripts/dropzone.js"></script>
    <script src="~/Scripts/chosen.jquery.min.js"></script>

    <script>
        var assetFlowStatus,institutionId, rowImageMG, rowImageAG, flagToCheckEditClickedMG = 'Novalue', flagToCheckEditClickedAG = 'Novalue';
        var assetStatusImageArray = [];
        var gnNumberImageArray = [];
        var crNumberImageArray = [];
        var courtOrderImageArray = [];
        var surveyNoImageArray = [];
        var khathaNoImageArray = [];
        var municipalNoImageArray = [];
        var northImageArray = [];
        var eastImageArray = [];
        var southImageArray = [];
        var westImageArray = [];
        var estimatedValueImageArray = [];
        var litigationManagementUploadImageArray = [];
        var litigationAssetUploadImageArray = [];
        var geoStampedUploadImageArray = [];
        var managementImageArray = [];
        var advisoryImageArray = [];

    </script>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Asset Managemet Portal", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@

                    @{


                        if (ViewBag.login == "Login")
                        {

                        }
                        else
                        {
                            <li id="homeBtn">@Html.ActionLink("Home", "OpenAccountPage", "AssetAccount")</li>
                        }
                    }

                </ul>


                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer></footer>
    </div>



</body>
</html>

AssetManagement/Views/Shared/_WebLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Asset management System</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link href="~/Content/jquery-ui.min.css" rel="stylesheet" />
    @*<link href="~/Map/css/map.css" rel="stylesheet" />*@
    @*<link href="~/leaflet/css/leaflet.css" rel="stylesheet" />*@
    <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css" />
    <link href="~/leaflet/css/leaflet.extra-markers.min.css" rel="stylesheet" />
    <link href="~/font-awesome-4.5.0/css/font-awesome.css" rel="stylesheet" />
    <link href="~/pwgSlideShow/pgwslideshow.min.css" rel="stylesheet" />
    <link href="~/leaflet/mousePointer/Control.Coordinates.css" rel="stylesheet" />
    <link href="~/leaflet/measurement/leaflet-measure.css" rel="stylesheet" />
    <link href="~/leaflet/measurePath/Leaflet.draw/leaflet.draw.css" rel="stylesheet" />
    <link href="~/leaflet/measurePath/leaflet.measurecontrol.css" rel="stylesheet" />
    <link href="~/leaflet/css/leaflet-search.min.css" rel="stylesheet" />

    
    <style>
        
     body{
         padding: 0px !important;
     }
    
    /* Remove the jumbotron's default bottom margin */ 
    .jumbotron {
        padding:3px 0 3px 0 !important;
        margin-bottom: 0;
        background-color: #86A3FF !important;
    /*background: no-repeat url('../../Images/daria.jpeg') 50% / 100%;*/
    }
   
    /* Add a gray background color and some padding to the footer */
    footer {
        background-color: #f2f2f2;
        padding: 25px;
    }

    .container {    
        max-width:100%;
        padding-right:130px !important;
        padding-left:130px !important;
    }

    .customBg{
        background: #e1ffff; /* Old browsers */
        background: -moz-linear-gradient(-45deg,  #e1ffff 0%, #e1ffff 7%, #e1ffff 12%, #fdffff 12%, #e6f8fd 30%, #c8eefb 54%, #bee4f8 75%, #b1d8f5 100%); /* FF3.6-15 */
        background: -webkit-linear-gradient(-45deg,  #e1ffff 0%,#e1ffff 7%,#e1ffff 12%,#fdffff 12%,#e6f8fd 30%,#c8eefb 54%,#bee4f8 75%,#b1d8f5 100%); /* Chrome10-25,Safari5.1-6 */
        background: linear-gradient(135deg,  #e1ffff 0%,#e1ffff 7%,#e1ffff 12%,#fdffff 12%,#e6f8fd 30%,#c8eefb 54%,#bee4f8 75%,#b1d8f5 100%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
        filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#e1ffff', endColorstr='#b1d8f5',GradientType=1 ); /* IE6-9 fallback on horizontal gradient */

    }

    .navBgCusotm{
        /* Permalink - use to edit and share this gradient: http://colorzilla.com/gradient-editor/#d64228+5,d45b48+30,d45b48+59,b93523+82,b83928+93,b63b30+100 */
        background: rgb(214,66,40); /* Old browsers */
        background: -moz-linear-gradient(-45deg,  rgba(214,66,40,1) 5%, rgba(212,91,72,1) 30%, rgba(212,91,72,1) 59%, rgba(185,53,35,1) 82%, rgba(184,57,40,1) 93%, rgba(182,59,48,1) 100%); /* FF3.6-15 */
        background: -webkit-linear-gradient(-45deg,  rgba(214,66,40,1) 5%,rgba(212,91,72,1) 30%,rgba(212,91,72,1) 59%,rgba(185,53,35,1) 82%,rgba(184,57,40,1) 93%,rgba(182,59,48,1) 100%); /* Chrome10-25,Safari5.1-6 */
        background: linear-gradient(135deg,  rgba(214,66,40,1) 5%,rgba(212,91,72,1) 30%,rgba(212,91,72,1) 59%,rgba(185,53,35,1) 82%,rgba(184,57,40,1) 93%,rgba(182,59,48,1) 100%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
        filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#d64228', endColorstr='#b63b30',GradientType=1 ); /* IE6-9 fallback on horizontal gradient */

    }

    .footerBgCustom{
        color:white;
        /* Permalink - use to edit and share this gradient: http://colorzilla.com/gradient-editor/#606c88+0,3f4c6b+100;Grey+3D+%232 */
        background: rgb(96,108,136); /* Old browsers */
        background: -moz-linear-gradient(-45deg,  rgba(96,108,136,1) 0%, rgba(63,76,107,1) 100%); /* FF3.6-15 */
        background: -webkit-linear-gradient(-45deg,  rgba(96,108,136,1) 0%,rgba(63,76,107,1) 100%); /* Chrome10-25,Safari5.1-6 */
        background: linear-gradient(135deg,  rgba(96,108,136,1) 0%,rgba(63,76,107,1) 100%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
        filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#606c88', endColorstr='#3f4c6b',GradientType=1 ); /* IE6-9 fallback on horizontal gradient */

    }

    .footerBgCustom p {
        margin:0px !important;
    }

    #headerCustom {
        background-image: url('../../Images/bg3.jpg');
        background-repeat: no-repeat;
        background-size: 100% 100%;

    }

    .nav-pills > li > a {
        border-radius: 0px !important;
    } 

    .nav-stacked > li {
        float: none;
        border: 1px solid #428BCA !important;
        margin-bottom: 7px;
    }
   
    .nav-pills > li.active > a, .nav-pills > li.active > a:hover, .nav-pills > li.active > a:focus {
        box-shadow:5px 5px 5px gray;
    }
    
    #horizontalNavCustom{
        float:none !important;
    }


    div.itemImage {
    display: inline-block;   
    }

    .caption {
        display: block;
    }

    div.polaroid {      
      box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.99), 0 6px 20px 0 rgba(0, 0, 0,0.99);      
      padding:5px;
    }

    div.polaroidOnMap {      
      padding:5px;
      border-radius:4px;
      box-shadow: 0 1px 5px rgba(0,0,0,0.65);
    }

    .navbar {
        z-index:0 !important;
        margin-bottom:10px;
        min-height:30px !important;
        height:35px !important;
    }

    .navbar-default .navbar-nav > li > a {
        color: #ffffff;
        font-weight: bold;
        font-size: 16px;        
    }

    .navbar-nav > li > a {
        line-height: 5px;
    }
    .navbar-default .navbar-nav > .active > a, .navbar-default .navbar-nav > .active > a:hover, .navbar-default .navbar-nav > .active > a:focus {
        color: #ffffff;
        background-color:#124ca0;
        line-height: 3px;
    }

   
    #headerContainerCustom{
        padding-right:0px !important;
        padding-left:0px !important;
        padding : 0px !important;
    }
        
</style>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <!-- Include Bootstrap Wizard -->
    <script src="~/Scripts/jquery-ui.min.js"></script>
    @*<script src="~/Map/js/lib/d3.v3.min.js"></script>
    <script src="~/Map/js/lib/topojson.v1.min.js"></script>
    <script src="~/Map/js/map.js"></script>*@
    <script src="~/leaflet/mapData/geojson/Karnataka_District.js"></script>
    <script src="~/leaflet/mapData/geojson/Karnataka_Mandya.js"></script>
    @*<script src="~/leaflet/js/leaflet.js"></script>*@
    <script src="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js"></script>
    <script src="~/leaflet/js/leaflet.extra-markers.min.js"></script>
    <script src="~/leaflet/mousePointer/util/NumberFormatter.js"></script>
    <script src="~/leaflet/mousePointer/Control.Coordinates.js"></script>
    <script src="~/leaflet/measurement/leaflet-measure.min.js"></script>
    <script src="~/leaflet/measurePath/Leaflet.draw/leaflet.draw.js"></script>
    <script src="~/leaflet/measurePath/leaflet.measurecontrol.js"></script>
    <script src="~/leaflet/js/leaflet-search.min.js"></script>
    <script src="~/leaflet/js/easy-button.js"></script>
    <script src="~/leaflet/js/leafletmap.js"></script>
    <script src="~/pwgSlideShow/pgwslideshow.min.js"></script>
    <script src="~/Scripts/jQuery.print.js"></script>


    <div class="jumbotron" id="headerCustom">
        <div class="container" id="headerContainerCustom">
            <div class="col-sm-3 itemImage" style="text-align:left">
                <img src="~/Images/kreis_logo.png" height="130" width="130" />
                @*<span class="caption" style="margin-left:4%;color:white;font-size:12px">Govt. Of Karnataka</span>*@
            </div>
            <div class="col-sm-6" style="text-align:center">
                <h2 style="margin-top: 0px;color:white;font-weight: bold;font-size:42px">Asset Management System </h2>
                <h3 style="margin-top: 0px;color:white">Hazrath Tippu Sultan Shaheed Wakf Estate </h3>
                <h3 style="margin-top: 0px;color:white">حضرت ٹیپو سلطان شہید وقف اسٹیٹ</h3>
            </div>
            <div class="col-sm-3 itemImage" style="text-align:right">
                <img src="~/Images/tippu.png" height="130" width="150" />
                @*<span class="caption" style="margin-right:15%;color:white;font-size:12px">Tippu Sultan</span>*@
            </div>
        </div>
    </div>

    <div class="container customBg">
        
        <div class="polaroid">
            <nav class="navbar navbar-default navBgCusotm">
                <div class="container-fluid ">

                    <ul id="horizontalNavCustom" class="nav navbar-nav ">
                        @*<li id="homeNavBtn">@Html.ActionLink("Home","Index", "Home")</li>*@
                        <li id="homeNavBtn">
                            <a href="/Home/Index" style="height:35px">
                                <i class="fa fa-home  fa-2x" aria-hidden="true" style="margin-top:-48%"></i>
                            </a>
                        </li>
                        <li><a style="color: #777777;">About</a></li>
                        <li id="dataVerifyBtn">@Html.ActionLink("Data Verify Form", "OpenDataVerifyPage", "Home")</li>
                        <li><a style="color: #777777;">Downloads</a></li>
                        <li><a style="color: #777777;">RTI</a></li>
                        <li id="contactUsBtn">@Html.ActionLink("Contact Us", "Contact", "Home")</li>
                        <li><a style="color: #777777;">Report</a></li>
                        <li id="mapNavBtn">@Html.ActionLink("Map", "Index", "Home")</li>


                        <li id="loginNavBtn" style="float:right;">@Html.ActionLink("Log In", "OpenLogin", "LoginReg")</li>
                    </ul>
                </div>
            </nav>

            <div class="row">
                   @RenderBody()
            </div>
            
        </div>
    </div>

    <footer class="footerBgCustom" style="max-height:80px;text-align:center;font-size:12px;padding:0px">
        <p>Copyright (c) 2016 | Designed & Hosted By : Microline Electronics (P) Ltd, Bengaluru</p>
        <p>DISCLAIMER</p>
        <p> Content Owned, Maintained and Updated by Hazrath Tippu Sultan Shahees Wakf Estate, Srirangapatna</p>
        <p> Questions regarding content or presentation may be mail to: hazrathtipusultan.wakfestate@gmail.com  </p>
    </footer>

</body>
</html>